# ----------------------------------------------------------------------
# |
# |  release_sources.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2024-03-02 10:25:37
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2024
# |  Distributed under the MIT License.
# |
# ----------------------------------------------------------------------

# Changes to any file or a file within a directory will trigger a release.
src:
  - 'src/**'
  - 'pyproject.toml'
  - 'README.md'
